language: java

jdk: 
    - oraclejdk8

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
  sonarqube:
    organization: "305"

script:
    - mvn -f SACO/pom.xml clean install
    - sonar-scanner
